version: '3.8'

services:
  spring-boot:
    build:
      context: ./todo-app
      dockerfile: Dockerfile
    ports:
      - 9090:9090
    command:
      sh -c "mvn test && mvn clean spring-boot:run"
    volumes:
      - ./todo-app:/app